### ISSUE TITLE
Python 3.7 isn't easily available on all platforms

### ISSUE THREAD

**Issue by PeterJCLaw** [RealOrangeOne/mkdocs-sr-demo#1]
Can we depend on Python 3.6 (or, ideally, Python 3.5) instead?

**Comment by RealOrangeOne** [comment]
3.7 is the default on my system, but Arch is known for using bleeding edge versions. 3.5 sounds like a reasonable version (I know that's default in Debian stretch). Unfortunately `Pipfile` doesn't have a specification for doing wildcard versions (`>=3.5`). 

Pipenv installs the version of python specifically in the virtualenv for itself, so I don't _believe_ it matters about how available it is on platforms (ie in distro repos), pipenv just _handles_ it. I'd be interested to know if this happens on a machine other than my own, though. (I believe `pipenv` has a version of `pyenv` baked in, which loads the specific version directly)

**Comment by PeterJCLaw** [comment]
> Unfortunately `Pipfile` doesn't have a specification for doing wildcard versions (`>=3.5`).

This feels like a fairly major oversight!

From what I can tell, `pipenv` isn't able to install Python versions:
```
$ pipenv install --dev
Warning: Python 3.7 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```

However if I install it into a Python 3.5 environment and then run it, it does seem happy to ignore the Python version number specified.

**Comment by RealOrangeOne** [comment]
Interestingly, it turns out that the `python_requires` argument is completely optional. If ommitted, it just uses the system version of python instead, which is great!

Although, for me, `/usr/bin/python` (which it claims to use) is a `3.7` (yes, that goes against PEP394). I'd be interested to know what it does on a system with `/usr/bin/python` set to a `2.7` version.

It looks like setting the version to simply `3` will work, and just install a version of `python3` (hopefully resolving the above). Pushed up a commit with that amendment now, would be interested to see your mileage with that change.

**Comment by PeterJCLaw** [comment]
I created a pair of virtualenvs from which to run `pipenv` -- a Python 2 and a Python 3.5 (the Ubuntu 16.04 defaults) -- and a pair of clones to work in (so they wouldn't interfere). The result was the same in both cases -- it created a virtualenv using the Python 3.6 (which I also have installed).

**Comment by RealOrangeOne** [comment]
Perfect, in that case I think we can consider this issue resolved. `Pipenv` will just use the latest verison of Python 3 it can find. `mkdocs` supports `>=3.5` (https://github.com/mkdocs/mkdocs/blob/master/setup.py#L67), which is a fine requirement. Although, I do think we should document that incase someone has an older version installed.
